import type { Rules } from '../types'

export const htmlRecommendedRules: Rules = {
	// Begin expansion '@html-eslint/eslint-plugin' 'flat/recommended'
	'html/require-lang': 'error',
	'html/require-img-alt': 'error',
	'html/require-doctype': 'error',
	'html/require-title': 'error',
	'html/no-multiple-h1': 'error',
	'html/no-extra-spacing-tags': 'error',
	'html/attrs-newline': 'error',
	'html/element-newline': ['error', { inline: ['$inline'] }],
	'html/no-duplicate-id': 'error',
	'html/indent': 'error',
	'html/require-li-container': 'error',
	'html/quotes': 'error',
	'html/no-obsolete-tags': 'error',
	'html/no-obsolete-attrs': 'error',
	'html/require-closing-tags': 'error',
	'html/no-duplicate-attrs': 'error',
	'html/use-baseline': 'error',
	'html/no-duplicate-in-head': 'error',
	// End expansion
}

export const htmlAllRules: Rules = {
	// Begin expansion '@html-eslint/eslint-plugin' 'flat/all'
	'html/require-lang': 'error',
	'html/require-img-alt': 'error',
	'html/require-doctype': 'error',
	'html/require-title': 'error',
	'html/no-duplicate-id': 'error',
	'html/no-inline-styles': 'error',
	'html/no-multiple-h1': 'error',
	'html/no-extra-spacing-tags': 'error',
	'html/no-extra-spacing-text': 'error',
	'html/attrs-newline': 'error',
	'html/element-newline': 'error',
	'html/no-skip-heading-levels': 'error',
	'html/require-li-container': 'error',
	'html/indent': 'error',
	'html/quotes': 'error',
	'html/id-naming-convention': 'error',
	'html/no-obsolete-tags': 'error',
	'html/require-attrs': 'error',
	'html/require-closing-tags': 'error',
	'html/require-meta-description': 'error',
	'html/require-frame-title': 'error',
	'html/no-non-scalable-viewport': 'error',
	'html/no-positive-tabindex': 'error',
	'html/require-meta-viewport': 'error',
	'html/require-meta-charset': 'error',
	'html/no-target-blank': 'error',
	'html/no-duplicate-attrs': 'error',
	'html/no-abstract-roles': 'error',
	'html/require-button-type': 'error',
	'html/no-aria-hidden-body': 'error',
	'html/no-aria-hidden-on-focusable': 'error',
	'html/no-multiple-empty-lines': 'error',
	'html/no-accesskey-attrs': 'error',
	'html/no-restricted-attrs': 'error',
	'html/no-trailing-spaces': 'error',
	'html/no-restricted-attr-values': 'error',
	'html/no-script-style-type': 'error',
	'html/no-heading-inside-button': 'error',
	'html/no-invalid-role': 'error',
	'html/no-nested-interactive': 'error',
	'html/lowercase': 'error',
	'html/require-open-graph-protocol': 'error',
	'html/require-form-method': 'error',
	'html/sort-attrs': 'error',
	'html/prefer-https': 'error',
	'html/require-input-label': 'error',
	'html/max-element-depth': 'error',
	'html/require-explicit-size': 'error',
	'html/use-baseline': 'error',
	'html/no-duplicate-class': 'error',
	'html/no-empty-headings': 'error',
	'html/require-content': 'error',
	'html/no-invalid-entity': 'error',
	'html/no-duplicate-in-head': 'error',
	'html/no-ineffective-attrs': 'error',
	'html/no-restricted-tags': 'error',
	'html/no-whitespace-only-children': 'error',
	'html/no-obsolete-attrs': 'error',
	'html/class-spacing': 'error',
	'html/css-no-empty-blocks': 'error',
	'html/no-redundant-role': 'error',
	'html/no-invalid-attr-value': 'error',
	'html/head-order': 'error',
	'html/require-details-summary': 'error',
	'html/svg-require-viewbox': 'error',
	// End expansion
}
