import type { Rules } from '../types'

// Note that 'json-package/order-properties' defaults to 'sort-package-json'
export const jsonPackageRecommendedRules: Rules = {
	// Begin expansion 'eslint-plugin-package-json' 'configs.recommended.rules'
	'json-package/no-empty-fields': 'error',
	'json-package/no-redundant-files': 'error',
	'json-package/no-redundant-publishConfig': 'error',
	'json-package/order-properties': 'error',
	'json-package/require-description': 'error',
	'json-package/require-license': 'error',
	'json-package/require-name': 'error',
	'json-package/require-type': 'error',
	'json-package/require-version': 'error',
	'json-package/repository-shorthand': 'error',
	'json-package/sort-collections': 'error',
	'json-package/specify-peers-locally': 'error',
	'json-package/unique-dependencies': 'error',
	'json-package/valid-author': 'error',
	'json-package/valid-bin': 'error',
	'json-package/valid-bundleDependencies': 'error',
	'json-package/valid-config': 'error',
	'json-package/valid-contributors': 'error',
	'json-package/valid-cpu': 'error',
	'json-package/valid-description': 'error',
	'json-package/valid-dependencies': 'error',
	'json-package/valid-devDependencies': 'error',
	'json-package/valid-directories': 'error',
	'json-package/valid-engines': 'error',
	'json-package/valid-exports': 'error',
	'json-package/valid-files': 'error',
	'json-package/valid-homepage': 'error',
	'json-package/valid-keywords': 'error',
	'json-package/valid-license': 'error',
	'json-package/valid-main': 'error',
	'json-package/valid-man': 'error',
	'json-package/valid-optionalDependencies': 'error',
	'json-package/valid-os': 'error',
	'json-package/valid-peerDependencies': 'error',
	'json-package/valid-private': 'error',
	'json-package/valid-publishConfig': 'error',
	'json-package/valid-repository': 'error',
	'json-package/valid-scripts': 'error',
	'json-package/valid-sideEffects': 'error',
	'json-package/valid-type': 'error',
	'json-package/valid-workspaces': 'error',
	'json-package/valid-name': 'error',
	'json-package/valid-repository-directory': 'error',
	'json-package/valid-version': 'error',
	// End expansion
}
