import type { Rules } from '../types'

// Note that 'json-package/order-properties' defaults to 'sort-package-json'
export const jsonPackageRecommendedRules: Rules = {
	// Begin expansion 'eslint-plugin-package-json' 'configs.recommended.rules'
	'json-package/no-empty-fields': 'error',
	'json-package/no-redundant-files': 'error',
	'json-package/order-properties': 'error',
	'json-package/require-description': 'error',
	'json-package/require-name': 'error',
	'json-package/require-type': 'error',
	'json-package/require-version': 'error',
	'json-package/repository-shorthand': 'error',
	'json-package/sort-collections': 'error',
	'json-package/unique-dependencies': 'error',
	'json-package/valid-author': 'error',
	'json-package/valid-bundleDependencies': 'error',
	'json-package/valid-config': 'error',
	'json-package/valid-cpu': 'error',
	'json-package/valid-dependencies': 'error',
	'json-package/valid-description': 'error',
	'json-package/valid-devDependencies': 'error',
	'json-package/valid-directories': 'error',
	'json-package/valid-exports': 'error',
	'json-package/valid-license': 'error',
	'json-package/valid-optionalDependencies': 'error',
	'json-package/valid-peerDependencies': 'error',
	'json-package/valid-scripts': 'error',
	'json-package/valid-type': 'error',
	'json-package/valid-bin': 'error',
	'json-package/valid-name': 'error',
	'json-package/valid-package-definition': [
		'error',
		{
			ignoreProperties: [
				'author',
				'bundleDependencies',
				'config',
				'cpu',
				'dependencies',
				'description',
				'devDependencies',
				'directories',
				'exports',
				'license',
				'optionalDependencies',
				'peerDependencies',
				'scripts',
				'type',
				'bin',
				'name',
				'repository-directory',
				'version',
			],
		},
	],
	'json-package/valid-repository-directory': 'error',
	'json-package/valid-version': 'error',
	// End expansion
}
