import type { Rules } from '../types'

export const svelteRecommendedRules: Rules = {
	// Brittle since there's no negative index access in dot-prop
	// Begin expansion 'eslint-plugin-svelte' 'flat/recommended[3]'
	'svelte/comment-directive': 'error',
	'svelte/infinite-reactive-loop': 'error',
	'svelte/no-at-debug-tags': 'warn',
	'svelte/no-at-html-tags': 'error',
	'svelte/no-dom-manipulating': 'error',
	'svelte/no-dupe-else-if-blocks': 'error',
	'svelte/no-dupe-on-directives': 'error',
	'svelte/no-dupe-style-properties': 'error',
	'svelte/no-dupe-use-directives': 'error',
	'svelte/no-export-load-in-svelte-module-in-kit-pages': 'error',
	'svelte/no-immutable-reactive-statements': 'error',
	'svelte/no-inner-declarations': 'error',
	'svelte/no-inspect': 'warn',
	'svelte/no-navigation-without-resolve': 'error',
	'svelte/no-not-function-handler': 'error',
	'svelte/no-object-in-text-mustaches': 'error',
	'svelte/no-raw-special-elements': 'error',
	'svelte/no-reactive-functions': 'error',
	'svelte/no-reactive-literals': 'error',
	'svelte/no-reactive-reassign': 'error',
	'svelte/no-shorthand-style-property-overrides': 'error',
	'svelte/no-store-async': 'error',
	'svelte/no-svelte-internal': 'error',
	'svelte/no-unknown-style-directive-property': 'error',
	'svelte/no-unnecessary-state-wrap': 'error',
	'svelte/no-unused-props': 'error',
	'svelte/no-unused-svelte-ignore': 'error',
	'svelte/no-useless-children-snippet': 'error',
	'svelte/no-useless-mustaches': 'error',
	'svelte/prefer-svelte-reactivity': 'error',
	'svelte/prefer-writable-derived': 'error',
	'svelte/require-each-key': 'error',
	'svelte/require-event-dispatcher-types': 'error',
	'svelte/require-store-reactive-access': 'error',
	'svelte/system': 'error',
	'svelte/valid-each-key': 'error',
	'svelte/valid-prop-names-in-kit-pages': 'error',
	// End expansion
}

export const svelteAllRules: Rules = {
	// Brittle since there's no negative index access in dot-prop
	// Begin expansion 'eslint-plugin-svelte' 'flat/all[3]'
	'svelte/@typescript-eslint/no-unnecessary-condition': 'error',
	'svelte/block-lang': 'error',
	'svelte/button-has-type': 'error',
	'svelte/comment-directive': 'error',
	'svelte/consistent-selector-style': 'error',
	'svelte/derived-has-same-inputs-outputs': 'error',
	'svelte/experimental-require-slot-types': 'error',
	'svelte/experimental-require-strict-events': 'error',
	'svelte/first-attribute-linebreak': 'error',
	'svelte/html-closing-bracket-new-line': 'error',
	'svelte/html-closing-bracket-spacing': 'error',
	'svelte/html-quotes': 'error',
	'svelte/html-self-closing': 'error',
	'svelte/indent': 'error',
	'svelte/infinite-reactive-loop': 'error',
	'svelte/max-attributes-per-line': 'error',
	'svelte/max-lines-per-block': 'error',
	'svelte/mustache-spacing': 'error',
	'svelte/no-add-event-listener': 'error',
	'svelte/no-at-const-tags': 'error',
	'svelte/no-at-debug-tags': 'error',
	'svelte/no-at-html-tags': 'error',
	'svelte/no-bind-value-on-checkable-inputs': 'error',
	'svelte/no-conflicting-module-names': 'error',
	'svelte/no-dom-manipulating': 'error',
	'svelte/no-dupe-else-if-blocks': 'error',
	'svelte/no-dupe-on-directives': 'error',
	'svelte/no-dupe-style-properties': 'error',
	'svelte/no-dupe-use-directives': 'error',
	'svelte/no-dynamic-slot-name': 'error',
	'svelte/no-export-load-in-svelte-module-in-kit-pages': 'error',
	'svelte/no-extra-reactive-curlies': 'error',
	'svelte/no-goto-without-base': 'error',
	'svelte/no-ignored-unsubscribe': 'error',
	'svelte/no-immutable-reactive-statements': 'error',
	'svelte/no-inline-styles': 'error',
	'svelte/no-inner-declarations': 'error',
	'svelte/no-inspect': 'error',
	'svelte/no-navigation-without-base': 'error',
	'svelte/no-navigation-without-resolve': 'error',
	'svelte/no-nested-style-tag': 'error',
	'svelte/no-not-function-handler': 'error',
	'svelte/no-object-in-text-mustaches': 'error',
	'svelte/no-raw-special-elements': 'error',
	'svelte/no-reactive-functions': 'error',
	'svelte/no-reactive-literals': 'error',
	'svelte/no-reactive-reassign': 'error',
	'svelte/no-shorthand-style-property-overrides': 'error',
	'svelte/no-spaces-around-equal-signs-in-attribute': 'error',
	'svelte/no-store-async': 'error',
	'svelte/no-svelte-internal': 'error',
	'svelte/no-target-blank': 'error',
	'svelte/no-top-level-browser-globals': 'error',
	'svelte/no-trailing-spaces': 'error',
	'svelte/no-unknown-style-directive-property': 'error',
	'svelte/no-unnecessary-state-wrap': 'error',
	'svelte/no-unused-class-name': 'error',
	'svelte/no-unused-props': 'error',
	'svelte/no-unused-svelte-ignore': 'error',
	'svelte/no-useless-children-snippet': 'error',
	'svelte/no-useless-mustaches': 'error',
	'svelte/prefer-attribute-interpolation': 'error',
	'svelte/prefer-class-directive': 'error',
	'svelte/prefer-const': 'error',
	'svelte/prefer-derived-over-derived-by': 'error',
	'svelte/prefer-destructured-store-props': 'error',
	'svelte/prefer-style-directive': 'error',
	'svelte/prefer-svelte-reactivity': 'error',
	'svelte/prefer-writable-derived': 'error',
	'svelte/require-each-key': 'error',
	'svelte/require-event-dispatcher-types': 'error',
	'svelte/require-event-prefix': 'error',
	'svelte/require-optimized-style-attribute': 'error',
	'svelte/require-store-callbacks-use-set-param': 'error',
	'svelte/require-store-reactive-access': 'error',
	'svelte/require-stores-init': 'error',
	'svelte/shorthand-attribute': 'error',
	'svelte/shorthand-directive': 'error',
	'svelte/sort-attributes': 'error',
	'svelte/spaced-html-comment': 'error',
	'svelte/system': 'error',
	'svelte/valid-compile': 'error',
	'svelte/valid-each-key': 'error',
	'svelte/valid-prop-names-in-kit-pages': 'error',
	'svelte/valid-style-parse': 'error',
	// End expansion
}
