import type { Rules } from '../types'

// Rules are fished out of eslint-config-xo's config array by index since
// presets aren't exported individually (eslint-config-xo-typescript was merged
// into eslint-config-xo in 2026). Index breadcrumbs note each entry's `name` at
// generation time — verify against the package if expansion output looks off.
// Plugin opinion layers are excluded from the base expansion: unicorn, import,
// node, and eslint-comments authority stays with this config's own presets, and
// the no-use-extend-native and xo plugins aren't registered here.

// Many are skipped on account of our managing these concerns elsewhere (or not
// at all). NOte that config order shifted with the addition of xo/css in in 72.0.0.

// [0] xo/ignores - Skipped
// [1] xo/ava - Skipped
// [2] xo/ava-package-json - Skipped
// [3] node-test/recommended - Skipped
// [4] xo/base - Included
// [5] xo/json - Skipped
// [6] xo/json5 - Skipped
// [7] xo/jsonc - Skipped
// [8] xo/package-json - Skipped
// [9] xo/regexp - Skipped
// [10] xo/jsdoc - Skipped
// [11] xo/jsdoc-typescript - Skipped
// [12] xo/html - Skipped
// [13] xo/markdown - Skipped
// [14] xo/css - Skipped (New in 72!)
// [15] xo/typescript - Included
// [16] xo/typescript-declaration - Included
// [17] xo/typescript-test-declaration - Included
// [18] xo/typescript-jsx - Included
// [19] xo/config-file - Skipped

// (xo/base)
export const xoJavascriptRules: Rules = {
	// Begin expansion 'eslint-config-xo' '[4].rules' 'exclude: @eslint-community/eslint-comments/, import-x/, n/, no-use-extend-native/, unicorn/, xo/'
	'logical-assignment-operators': 'off',
	'no-negated-condition': 'off',
	'no-nested-ternary': 'off',
	'no-process-exit': 'off',
	'function-call-argument-newline': 'off',
	// "@stylistic/comma-dangle":["error","always-multiline"],
	'for-direction': 'error',
	'getter-return': 'error',
	'no-async-promise-executor': 'error',
	'no-await-in-loop': 'error',
	'no-compare-neg-zero': 'error',
	'no-cond-assign': 'error',
	'no-constant-condition': 'error',
	'no-control-regex': 'error',
	'no-debugger': 'error',
	'no-dupe-args': 'error',
	'no-dupe-else-if': 'error',
	'no-dupe-keys': 'error',
	'no-duplicate-case': 'error',
	'no-empty-character-class': 'error',
	'no-empty': ['error', { allowEmptyCatch: true }],
	'no-empty-static-block': 'error',
	'no-ex-assign': 'error',
	'no-extra-boolean-cast': 'error',
	// "@stylistic/no-extra-semi":"error",
	'no-func-assign': 'error',
	'no-import-assign': 'error',
	'no-inner-declarations': 'error',
	'no-invalid-regexp': 'error',
	'no-irregular-whitespace': 'error',
	'no-loss-of-precision': 'error',
	'no-misleading-character-class': 'error',
	'no-obj-calls': 'error',
	'no-promise-executor-return': 'error',
	'no-prototype-builtins': 'error',
	'no-regex-spaces': 'error',
	'no-setter-return': 'error',
	'no-sparse-arrays': 'error',
	'no-template-curly-in-string': 'error',
	'no-unreachable': 'error',
	'no-unreachable-loop': 'error',
	'no-unsafe-finally': 'error',
	'no-unsafe-negation': ['error', { enforceForOrderingRelations: true }],
	'no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
	'no-unused-private-class-members': 'error',
	'no-useless-backreference': 'error',
	'use-isnan': 'error',
	'valid-typeof': ['error', { requireStringLiterals: false }],
	'no-unexpected-multiline': 'error',
	'accessor-pairs': ['error', { enforceForClassMembers: true }],
	'array-callback-return': ['error', { allowImplicit: true }],
	'block-scoped-var': 'error',
	complexity: 'warn',
	curly: 'error',
	'default-case': 'error',
	'default-case-last': 'error',
	'dot-notation': 'error',
	// "@stylistic/curly-newline":["error",{"consistent":true}],
	// "@stylistic/dot-location":["error","property"],
	eqeqeq: 'error',
	'grouped-accessor-pairs': ['error', 'getBeforeSet'],
	'guard-for-in': 'error',
	'no-alert': 'error',
	'no-caller': 'error',
	'no-case-declarations': 'error',
	'no-constructor-return': 'error',
	'no-else-return': ['error', { allowElseIf: false }],
	'no-empty-pattern': 'error',
	'no-eq-null': 'error',
	'no-eval': 'error',
	'no-extend-native': 'error',
	'no-extra-bind': 'error',
	'no-extra-label': 'error',
	'no-fallthrough': 'error',
	// "@stylistic/no-floating-decimal":"error",
	'no-global-assign': 'error',
	'no-implicit-coercion': 'error',
	'no-implicit-globals': 'error',
	'no-implied-eval': 'error',
	'no-iterator': 'error',
	'no-labels': 'error',
	'no-lone-blocks': 'error',
	// "@stylistic/no-multi-spaces":"error",
	'no-multi-str': 'error',
	'no-new-func': 'error',
	'no-new-wrappers': 'error',
	'no-nonoctal-decimal-escape': 'error',
	'no-object-constructor': 'error',
	'no-new': 'error',
	'no-octal-escape': 'error',
	'no-octal': 'error',
	'no-proto': 'error',
	'no-redeclare': 'error',
	'no-return-assign': ['error', 'always'],
	'no-script-url': 'error',
	'no-self-assign': ['error', { props: true }],
	'no-self-compare': 'error',
	'no-sequences': ['error', { allowInParentheses: false }],
	'no-throw-literal': 'error',
	'no-unmodified-loop-condition': 'error',
	'no-unused-expressions': ['error', { enforceForJSX: true }],
	'no-unused-labels': 'error',
	'no-useless-call': 'error',
	'no-useless-catch': 'error',
	'no-useless-concat': 'error',
	'no-useless-escape': 'error',
	'no-useless-return': 'error',
	'no-void': 'error',
	'no-warning-comments': 'warn',
	'no-with': 'error',
	'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
	'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
	radix: 'error',
	'require-unicode-regexp': ['error', { requireFlag: 'v' }],
	// "@stylistic/wrap-iife":["error","inside",{"functionPrototypeMethods":true}],
	yoda: 'error',
	'no-delete-var': 'error',
	'no-label-var': 'error',
	'no-shadow': ['error', { ignoreOnInitialization: true }],
	'no-shadow-restricted-names': 'error',
	'no-undef-init': 'error',
	'no-undef': ['error', { typeof: true }],
	'no-unused-vars': [
		'error',
		{
			vars: 'all',
			varsIgnorePattern: '^_',
			args: 'after-used',
			ignoreRestSiblings: true,
			argsIgnorePattern: '^_',
			caughtErrors: 'all',
			caughtErrorsIgnorePattern: '^_$',
		},
	],
	'no-restricted-imports': [
		'error',
		'domain',
		'freelist',
		'smalloc',
		'punycode',
		'sys',
		'querystring',
		'colors',
		{ name: 'mkdirp', message: 'Use `fs.mkdir` with `{recursive: true}` instead.' },
		{ name: 'rimraf', message: 'Use `fs.rm` with `{recursive: true}` instead.' },
		{ name: 'object-assign', message: 'Use `Object.assign()` or object spread instead.' },
		{ name: 'xtend', message: 'Use `Object.assign()` or object spread instead.' },
		{ name: 'extend-shallow', message: 'Use `Object.assign()` or object spread instead.' },
		{ name: 'left-pad', message: 'Use `String.prototype.padStart()` instead.' },
		{ name: 'pad-left', message: 'Use `String.prototype.padStart()` instead.' },
		{ name: 'right-pad', message: 'Use `String.prototype.padEnd()` instead.' },
		{ name: 'pad-right', message: 'Use `String.prototype.padEnd()` instead.' },
		{ name: 'safe-buffer', message: 'Use `Buffer.alloc()` or `Buffer.from()` instead.' },
		{ name: 'safer-buffer', message: 'Use `Buffer.alloc()` or `Buffer.from()` instead.' },
		{ name: 'buffer-alloc', message: 'Use `Buffer.alloc()` instead.' },
		{ name: 'array-flatten', message: 'Use `Array.prototype.flat()` instead.' },
		{ name: 'concat-map', message: 'Use `Array.prototype.flatMap()` instead.' },
		{
			name: 'pad',
			message: 'Use `String.prototype.padStart()` / `String.prototype.padEnd()` instead.',
		},
		{ name: 'co', message: 'Use async/await instead.' },
		{ name: 'inherits', message: 'Use `class extends` instead.' },
		{ name: 'windows-1252', message: 'Use `TextDecoder` instead.' },
		{ name: 'string_decoder', message: 'Use `TextDecoder` instead.' },
		{ name: 'isarray', message: 'Use `Array.isArray()` instead.' },
		{ name: 'object-keys', message: 'Use `Object.keys()` instead.' },
		{ name: 'object.assign', message: 'Use `Object.assign()` or object spread instead.' },
		{ name: 'globalthis', message: 'Use the `globalThis` global instead.' },
		{ name: 'es6-promise', message: 'Use `Promise` instead.' },
		{ name: 'abort-controller', message: 'Use the native `AbortController` instead.' },
		{ name: 'queue-microtask', message: 'Use `queueMicrotask()` instead.' },
		{ name: 'buffer-from', message: 'Use `Buffer.from()` instead.' },
		{ name: 'has', message: 'Use `Object.hasOwn()` instead.' },
		{ name: 'hasown', message: 'Use `Object.hasOwn()` instead.' },
		{ name: 'repeat-string', message: 'Use `String.prototype.repeat()` instead.' },
		{ name: 'path-parse', message: 'Use `path.parse()` instead.' },
		{ name: 'node.extend', message: 'Use `Object.assign()` or object spread instead.' },
		{ name: 'aggregate-error', message: 'Use the native `AggregateError` instead.' },
		{ name: 'is-nan', message: 'Use `Number.isNaN()` instead.' },
		{ name: 'is-finite', message: 'Use `Number.isFinite()` instead.' },
		{ name: 'object-is', message: 'Use `Object.is()` instead.' },
		{ name: 'defaults', message: 'Use `Object.assign()` instead.' },
		{ name: 'whatwg-url', message: 'Use the native `URL` API instead.' },
	],
	// "@stylistic/array-bracket-newline":["error","consistent"],
	// "@stylistic/array-bracket-spacing":["error","never"],
	// "@stylistic/array-element-newline":["error","consistent"],
	// "@stylistic/brace-style":["error","1tbs",{"allowSingleLine":true}],
	camelcase: ['error', { properties: 'always' }],
	'capitalized-comments': [
		'error',
		'always',
		{
			ignorePattern: String.raw`pragma|\w{1,40}[\-:]ignore|ignore|webpack\w+:|c8|v8|type-coverage:|const |let |var |import |export |function |class |if \(|for \(|while \(|switch \(`,
			ignoreInlineComments: true,
			ignoreConsecutiveComments: true,
		},
	],
	// "@stylistic/comma-spacing":["error",{"before":false,"after":true}],
	// "@stylistic/comma-style":["error","last"],
	// "@stylistic/computed-property-spacing":["error","never",{"enforceForClassMembers":true}],
	// "@stylistic/eol-last":"error",
	// "@stylistic/function-call-spacing":["error","never"],
	'func-name-matching': ['error', { considerPropertyDescriptor: true }],
	'func-names': ['error', 'never'],
	// "@stylistic/function-call-argument-newline":["error","consistent"],
	// "@stylistic/indent":["error","tab",{"SwitchCase":1}],
	// "@stylistic/jsx-quotes":["error","prefer-single"],
	// "@stylistic/key-spacing":["error",{"beforeColon":false,"afterColon":true}],
	// "@stylistic/keyword-spacing":"error",
	// "@stylistic/linebreak-style":["error","unix"],
	// "@stylistic/lines-between-class-members":["error",{"enforce":[{"blankLine":"always","prev":"*","next":"method"},{"blankLine":"always","prev":"method","next":"field"},{"blankLine":"never","prev":"field","next":"field"}]}],
	'max-depth': 'warn',
	// "@stylistic/max-len":["warn",{"code":200,"ignoreComments":true,"ignoreUrls":true}],
	'max-lines': ['warn', { max: 1500, skipComments: true }],
	'max-nested-callbacks': ['warn', 4],
	'max-params': ['warn', { max: 4 }],
	// "@stylistic/max-statements-per-line":"error",
	'new-cap': ['error', { newIsCap: true, capIsNew: true }],
	// "@stylistic/multiline-ternary":["error","always-multiline"],
	// "@stylistic/new-parens":"error",
	'no-array-constructor': 'error',
	'no-bitwise': 'error',
	'no-lonely-if': 'error',
	// "@stylistic/no-mixed-operators":["error",{"groups":[["+","-","*","/","%","**","??"],["&","|","^","~","<<",">>",">>>","??"],["==","!=","===","!==",">",">=","<","<=","??"],["&&","||","??"],["in","instanceof","??"]]}],
	// "@stylistic/no-mixed-spaces-and-tabs":"error",
	'no-multi-assign': 'error',
	// "@stylistic/no-multiple-empty-lines":["error",{"max":1}],
	// "@stylistic/no-whitespace-before-property":"error",
	// "@stylistic/no-trailing-spaces":"error",
	'no-unneeded-ternary': 'error',
	// "@stylistic/object-curly-spacing":["error","never"],
	// "@stylistic/object-curly-newline":["error",{"ObjectExpression":{"multiline":true,"minProperties":4,"consistent":true},"ObjectPattern":{"multiline":true,"consistent":true},"ImportDeclaration":{"multiline":true,"minProperties":4,"consistent":true},"ExportDeclaration":{"multiline":true,"minProperties":4,"consistent":true}}],
	'one-var': ['error', 'never'],
	// "@stylistic/one-var-declaration-per-line":"error",
	'operator-assignment': ['error', 'always'],
	// "@stylistic/operator-linebreak":["error","before"],
	// "@stylistic/padded-blocks":["error","never",{"allowSingleLineBlocks":false}],
	// "@stylistic/padding-line-between-statements":["error",{"blankLine":"always","prev":"multiline-block-like","next":"*"}],
	'prefer-exponentiation-operator': 'error',
	'prefer-object-spread': 'error',
	// "@stylistic/quote-props":["error","as-needed"],
	// "@stylistic/quotes":["error","single"],
	// "@stylistic/semi-spacing":["error",{"before":false,"after":true}],
	// "@stylistic/semi-style":["error","last"],
	// "@stylistic/semi":["error","always"],
	// "@stylistic/space-before-blocks":["error","always"],
	// "@stylistic/space-before-function-paren":["error",{"anonymous":"always","named":"never","asyncArrow":"always"}],
	// "@stylistic/space-in-parens":["error","never"],
	// "@stylistic/space-infix-ops":"error",
	// "@stylistic/space-unary-ops":"error",
	// "@stylistic/spaced-comment":["error","always",{"line":{"exceptions":["-","+","*"],"markers":["!","/","=>"]},"block":{"exceptions":["-","+","*"],"markers":["!","*"],"balanced":true}}],
	// "@stylistic/switch-colon-spacing":["error",{"after":true,"before":false}],
	// "@stylistic/template-tag-spacing":["error","never"],
	'unicode-bom': ['error', 'never'],
	'arrow-body-style': 'error',
	// "@stylistic/arrow-parens":["error","as-needed"],
	// "@stylistic/arrow-spacing":["error",{"before":true,"after":true}],
	// "@stylistic/block-spacing":["error","never"],
	'constructor-super': 'error',
	// "@stylistic/generator-star-spacing":["error","both"],
	'no-class-assign': 'error',
	'no-const-assign': 'error',
	'no-constant-binary-expression': ['error', { checkRelationalComparisons: true }],
	'no-dupe-class-members': 'error',
	'no-new-native-nonconstructor': 'error',
	'no-this-before-super': 'error',
	'no-unassigned-vars': 'error',
	'no-useless-computed-key': ['error', { enforceForClassMembers: true }],
	'no-useless-constructor': 'error',
	'no-useless-rename': 'error',
	'no-var': 'error',
	'object-shorthand': ['error', 'always', { avoidExplicitReturnArrows: true }],
	'prefer-arrow-callback': ['error', { allowNamedFunctions: true }],
	'prefer-const': ['error', { destructuring: 'all' }],
	'prefer-destructuring': [
		'error',
		{
			VariableDeclarator: { array: false, object: true },
			AssignmentExpression: { array: false, object: false },
		},
		{ enforceForRenamedProperties: false },
	],
	'prefer-numeric-literals': 'error',
	'prefer-object-has-own': 'error',
	'prefer-rest-params': 'error',
	'prefer-spread': 'error',
	'preserve-caught-error': 'error',
	'require-yield': 'error',
	// "@stylistic/rest-spread-spacing":["error","never"],
	'symbol-description': 'error',
	// "@stylistic/template-curly-spacing":"error",
	// "@stylistic/yield-star-spacing":["error","both"],
	// "@stylistic/indent-binary-ops":["error","tab"],
	'no-restricted-globals': [
		'error',
		{
			globals: [
				'event',
				{
					name: 'atob',
					message:
						'This API is deprecated. Use https://github.com/sindresorhus/uint8array-extras instead.',
				},
				{
					name: 'btoa',
					message:
						'This API is deprecated. Use https://github.com/sindresorhus/uint8array-extras instead.',
				},
			],
			checkGlobalObject: true,
		},
	],
	// End expansion
}

// (xo/typescript)
export const xoTypescriptRules: Rules = {
	// Begin expansion 'eslint-config-xo' '[15].rules'
	'ts/adjacent-overload-signatures': 'error',
	'ts/array-type': ['error', { default: 'array-simple' }],
	'ts/await-thenable': 'error',
	'ts/ban-ts-comment': [
		'error',
		{ 'ts-expect-error': 'allow-with-description', minimumDescriptionLength: 4 },
	],
	'ts/ban-tslint-comment': 'error',
	'ts/no-restricted-types': [
		'error',
		{
			types: {
				object: {
					message:
						'The `object` type is hard to use. Use `Record<string, unknown>` instead. See: https://github.com/typescript-eslint/typescript-eslint/pull/848',
					fixWith: 'Record<string, unknown>',
				},
				null: {
					message: 'Use `undefined` instead. See: https://github.com/sindresorhus/meta/issues/7',
					fixWith: 'undefined',
				},
				Buffer: {
					message:
						'Use Uint8Array instead. See: https://sindresorhus.com/blog/goodbye-nodejs-buffer',
					suggest: ['Uint8Array'],
				},
				'[]': "Don't use the empty array type `[]`. It only allows empty arrays. Use `SomeType[]` instead.",
				'[[]]':
					"Don't use `[[]]`. It only allows an array with a single element which is an empty array. Use `SomeType[][]` instead.",
				'[[[]]]': "Don't use `[[[]]]`. Use `SomeType[][][]` instead.",
				'[[[[]]]]': 'ur drunk 🤡',
				'[[[[[]]]]]': '🦄💥',
			},
		},
	],
	'ts/class-literal-property-style': ['error', 'getters'],
	'ts/consistent-generic-constructors': ['error', 'constructor'],
	'ts/consistent-indexed-object-style': 'error',
	'brace-style': 'off',
	// "@stylistic/brace-style":["error","1tbs",{"allowSingleLine":false}],
	'comma-dangle': 'off',
	// "@stylistic/comma-dangle":["error","always-multiline"],
	'comma-spacing': 'off',
	// "@stylistic/comma-spacing":["error",{"before":false,"after":true}],
	'default-param-last': 'off',
	'ts/default-param-last': 'error',
	'dot-notation': 'off',
	'ts/dot-notation': 'error',
	'ts/consistent-type-assertions': [
		'error',
		{ assertionStyle: 'as', objectLiteralTypeAssertions: 'allow-as-parameter' },
	],
	'ts/consistent-type-definitions': ['error', 'type'],
	'ts/consistent-type-exports': ['error', { fixMixedExportsWithInlineTypeSpecifier: true }],
	'ts/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
	'func-call-spacing': 'off',
	// "@stylistic/function-call-spacing":["error","never"],
	indent: 'off',
	// "@stylistic/indent":["error","tab",{"SwitchCase":1}],
	'keyword-spacing': 'off',
	// "@stylistic/keyword-spacing":"error",
	'lines-between-class-members': 'off',
	// "@stylistic/lines-between-class-members":["error","always",{"exceptAfterSingleLine":true}],
	// "@stylistic/member-delimiter-style":["error",{"multiline":{"delimiter":"semi","requireLast":true},"singleline":{"delimiter":"semi","requireLast":false}}],
	'ts/member-ordering': 'off',
	camelcase: 'off',
	'ts/naming-convention': [
		'error',
		{
			selector: [
				'variable',
				'function',
				'classProperty',
				'objectLiteralProperty',
				'parameterProperty',
				'classMethod',
				'objectLiteralMethod',
				'typeMethod',
				'accessor',
			],
			format: ['strictCamelCase'],
			leadingUnderscore: 'allowSingleOrDouble',
			trailingUnderscore: 'allow',
		},
		{
			selector: 'variable',
			modifiers: ['const', 'global'],
			format: ['strictCamelCase', 'UPPER_CASE'],
			leadingUnderscore: 'allowSingleOrDouble',
			trailingUnderscore: 'allow',
			filter: { regex: '[- ]', match: false },
		},
		{
			selector: 'classProperty',
			modifiers: ['static', 'readonly'],
			format: ['strictCamelCase', 'UPPER_CASE'],
			leadingUnderscore: 'allowSingleOrDouble',
			trailingUnderscore: 'allow',
			filter: { regex: '[- ]', match: false },
		},
		{ selector: 'typeLike', format: ['StrictPascalCase'] },
		{ selector: 'interface', filter: '^[A-HJ-Z]', format: ['StrictPascalCase'] },
		{ selector: 'typeParameter', filter: '^T$|^[A-Z][A-Za-z]+$', format: ['StrictPascalCase'] },
		{
			selector: [
				'classProperty',
				'objectLiteralProperty',
				'parameterProperty',
				'classMethod',
				'objectLiteralMethod',
				'typeMethod',
				'accessor',
			],
			format: null,
			modifiers: ['requiresQuotes'],
		},
	],
	'ts/no-base-to-string': 'error',
	'no-array-constructor': 'off',
	'ts/no-array-constructor': 'error',
	'ts/no-array-delete': 'error',
	'no-dupe-class-members': 'off',
	'ts/no-dupe-class-members': 'error',
	'ts/no-confusing-void-expression': 'error',
	'ts/no-deprecated': 'error',
	'ts/no-duplicate-enum-values': 'error',
	'ts/no-duplicate-type-constituents': 'error',
	'ts/no-dynamic-delete': 'error',
	'no-empty-function': 'off',
	'ts/no-empty-function': 'error',
	'ts/no-empty-object-type': 'error',
	'ts/no-extra-non-null-assertion': 'error',
	'no-extra-parens': 'off',
	'no-extra-semi': 'off',
	// "@stylistic/no-extra-semi":"error",
	'no-loop-func': 'off',
	'ts/no-loop-func': 'error',
	'ts/no-extraneous-class': [
		'error',
		{
			allowConstructorOnly: false,
			allowEmpty: false,
			allowStaticOnly: false,
			allowWithDecorator: true,
		},
	],
	'no-void': ['error', { allowAsStatement: true }],
	'ts/no-floating-promises': [
		'error',
		{ checkThenables: true, ignoreVoid: true, ignoreIIFE: true },
	],
	'ts/no-for-in-array': 'error',
	'ts/no-inferrable-types': 'error',
	'ts/no-meaningless-void-operator': 'error',
	'ts/no-misused-new': 'error',
	'ts/no-misused-promises': ['error', { checksConditionals: true, checksVoidReturn: false }],
	'ts/no-namespace': 'error',
	'ts/no-non-null-asserted-nullish-coalescing': 'error',
	'ts/no-non-null-asserted-optional-chain': 'error',
	'no-redeclare': 'off',
	'ts/no-redeclare': 'error',
	'no-shadow': 'off',
	'ts/no-shadow': ['error', { ignoreOnInitialization: true }],
	'no-restricted-imports': 'off',
	'ts/no-restricted-imports': [
		'error',
		{
			paths: [
				'domain',
				'freelist',
				'smalloc',
				'punycode',
				'sys',
				'querystring',
				'colors',
				{ name: 'mkdirp', message: 'Use `fs.mkdir` with `{recursive: true}` instead.' },
				{ name: 'rimraf', message: 'Use `fs.rm` with `{recursive: true}` instead.' },
				{ name: 'object-assign', message: 'Use `Object.assign()` or object spread instead.' },
				{ name: 'xtend', message: 'Use `Object.assign()` or object spread instead.' },
				{ name: 'extend-shallow', message: 'Use `Object.assign()` or object spread instead.' },
				{ name: 'left-pad', message: 'Use `String.prototype.padStart()` instead.' },
				{ name: 'pad-left', message: 'Use `String.prototype.padStart()` instead.' },
				{ name: 'right-pad', message: 'Use `String.prototype.padEnd()` instead.' },
				{ name: 'pad-right', message: 'Use `String.prototype.padEnd()` instead.' },
				{ name: 'safe-buffer', message: 'Use `Buffer.alloc()` or `Buffer.from()` instead.' },
				{ name: 'safer-buffer', message: 'Use `Buffer.alloc()` or `Buffer.from()` instead.' },
				{ name: 'buffer-alloc', message: 'Use `Buffer.alloc()` instead.' },
				{ name: 'array-flatten', message: 'Use `Array.prototype.flat()` instead.' },
				{ name: 'concat-map', message: 'Use `Array.prototype.flatMap()` instead.' },
				{
					name: 'pad',
					message: 'Use `String.prototype.padStart()` / `String.prototype.padEnd()` instead.',
				},
				{ name: 'co', message: 'Use async/await instead.' },
				{ name: 'inherits', message: 'Use `class extends` instead.' },
				{ name: 'windows-1252', message: 'Use `TextDecoder` instead.' },
				{ name: 'string_decoder', message: 'Use `TextDecoder` instead.' },
				{ name: 'isarray', message: 'Use `Array.isArray()` instead.' },
				{ name: 'object-keys', message: 'Use `Object.keys()` instead.' },
				{ name: 'object.assign', message: 'Use `Object.assign()` or object spread instead.' },
				{ name: 'globalthis', message: 'Use the `globalThis` global instead.' },
				{ name: 'es6-promise', message: 'Use `Promise` instead.' },
				{ name: 'abort-controller', message: 'Use the native `AbortController` instead.' },
				{ name: 'queue-microtask', message: 'Use `queueMicrotask()` instead.' },
				{ name: 'buffer-from', message: 'Use `Buffer.from()` instead.' },
				{ name: 'has', message: 'Use `Object.hasOwn()` instead.' },
				{ name: 'hasown', message: 'Use `Object.hasOwn()` instead.' },
				{ name: 'repeat-string', message: 'Use `String.prototype.repeat()` instead.' },
				{ name: 'path-parse', message: 'Use `path.parse()` instead.' },
				{ name: 'node.extend', message: 'Use `Object.assign()` or object spread instead.' },
				{ name: 'aggregate-error', message: 'Use the native `AggregateError` instead.' },
				{ name: 'is-nan', message: 'Use `Number.isNaN()` instead.' },
				{ name: 'is-finite', message: 'Use `Number.isFinite()` instead.' },
				{ name: 'object-is', message: 'Use `Object.is()` instead.' },
				{ name: 'defaults', message: 'Use `Object.assign()` instead.' },
				{ name: 'whatwg-url', message: 'Use the native `URL` API instead.' },
			],
		},
	],
	'ts/no-require-imports': 'error',
	'ts/no-this-alias': ['error', { allowDestructuring: true }],
	'no-throw-literal': 'off',
	'ts/only-throw-error': ['error', { allowThrowingUnknown: true, allowThrowingAny: false }],
	'ts/no-unnecessary-boolean-literal-compare': 'off',
	'no-constant-condition': 'error',
	'ts/no-unnecessary-qualifier': 'error',
	'ts/no-unnecessary-type-arguments': 'error',
	'ts/no-unnecessary-type-assertion': 'error',
	'ts/no-unnecessary-type-constraint': 'error',
	'ts/no-unnecessary-type-conversion': 'error',
	'ts/no-unsafe-argument': 'error',
	'ts/no-unsafe-assignment': 'error',
	'ts/no-unsafe-call': 'error',
	'ts/no-unsafe-declaration-merging': 'error',
	'ts/no-unsafe-enum-comparison': 'error',
	'ts/no-unsafe-function-type': 'error',
	'ts/no-unsafe-member-access': 'error',
	'ts/no-unsafe-return': 'error',
	'ts/no-useless-empty-export': 'error',
	'no-unused-expressions': 'off',
	'no-unused-private-class-members': 'off',
	'ts/no-unused-private-class-members': 'error',
	'ts/no-unused-expressions': 'error',
	'no-unused-vars': 'off',
	'no-useless-constructor': 'off',
	'ts/no-useless-constructor': 'error',
	'ts/no-useless-default-assignment': 'error',
	'object-curly-spacing': 'off',
	// "@stylistic/object-curly-spacing":["error","never"],
	'padding-line-between-statements': 'off',
	// "@stylistic/padding-line-between-statements":["error",{"blankLine":"always","prev":"multiline-block-like","next":"*"}],
	'ts/no-wrapper-object-types': 'error',
	'ts/non-nullable-type-assertion-style': 'error',
	'ts/prefer-as-const': 'error',
	'ts/prefer-find': 'error',
	'ts/prefer-for-of': 'error',
	'ts/prefer-function-type': 'error',
	'ts/prefer-includes': 'error',
	'ts/prefer-literal-enum-member': 'error',
	'ts/prefer-namespace-keyword': 'error',
	'ts/prefer-nullish-coalescing': [
		'error',
		{
			ignoreTernaryTests: false,
			ignoreConditionalTests: false,
			ignoreMixedLogicalExpressions: false,
		},
	],
	'ts/prefer-optional-chain': 'error',
	'prefer-promise-reject-errors': 'off',
	'ts/prefer-promise-reject-errors': 'error',
	'ts/prefer-readonly': 'error',
	'ts/prefer-reduce-type-parameter': 'error',
	'ts/prefer-string-starts-ends-with': 'error',
	'ts/promise-function-async': 'error',
	'ts/related-getter-setter-pairs': 'error',
	quotes: 'off',
	// "@stylistic/quotes":["error","single"],
	'ts/restrict-plus-operands': ['error', { allowAny: false }],
	'ts/restrict-template-expressions': ['error', { allowNumber: true }],
	'unicorn/no-useless-template-literals': 'off',
	'ts/no-unnecessary-template-expression': 'error',
	'ts/return-await': 'error',
	'unicorn/require-array-sort-compare': 'off',
	'ts/require-array-sort-compare': ['error', { ignoreStringArrays: true }],
	'space-before-function-paren': 'off',
	// "@stylistic/space-before-function-paren":["error",{"anonymous":"always","named":"never","asyncArrow":"always"}],
	'space-infix-ops': 'off',
	// "@stylistic/space-infix-ops":"error",
	semi: 'off',
	// "@stylistic/semi":["error","always"],
	'space-before-blocks': 'off',
	// "@stylistic/space-before-blocks":["error","always"],
	'ts/strict-boolean-expressions': [
		'error',
		{
			allowNullableBoolean: true,
			allowNullableObject: true,
			allowNumber: false,
			allowString: false,
		},
	],
	'ts/strict-void-return': 'error',
	'default-case': 'off',
	'ts/switch-exhaustiveness-check': [
		'error',
		{ allowDefaultCaseForExhaustiveSwitch: false, requireDefaultForNonUnion: true },
	],
	'ts/triple-slash-reference': ['error', { path: 'never', types: 'never', lib: 'never' }],
	// "@stylistic/type-annotation-spacing":"error",
	'regexp/prefer-regexp-exec': 'off',
	'ts/prefer-regexp-exec': 'error',
	'ts/prefer-return-this-type': 'error',
	'ts/unified-signatures': ['error', { ignoreDifferentlyNamedParameters: true }],
	'ts/use-unknown-in-catch-callback-variable': 'error',
	// "@stylistic/type-generic-spacing":"error",
	// "@stylistic/type-named-tuple-spacing":"error",
	'constructor-super': 'off',
	'getter-return': 'off',
	'no-class-assign': 'off',
	'no-const-assign': 'off',
	'no-dupe-args': 'off',
	'no-dupe-keys': 'off',
	'no-func-assign': 'off',
	'no-import-assign': 'off',
	'no-new-native-nonconstructor': 'off',
	'no-obj-calls': 'off',
	'no-setter-return': 'off',
	'no-this-before-super': 'off',
	'no-undef': 'off',
	'no-unreachable': 'off',
	'no-unsafe-negation': 'off',
	'no-with': 'off',
	'node/no-unsupported-features/es-syntax': 'off',
	'node/no-unsupported-features/es-builtins': 'off',
	'import/namespace': 'off',
	'import/named': 'off',
	'no-duplicate-imports': 'off',
	'unicorn/import-style': 'off',
	'import/extensions': 'off',
	'import/export': 'off',
	'import/default': 'off',
	// "@stylistic/operator-linebreak":["error","before",{"overrides":{"=":"after"}}],
	// "@stylistic/indent-binary-ops":["error","tab"],
	// End expansion
}

// (xo/typescript-declaration)
export const xoTypescriptDtsRules: Rules = {
	// Begin expansion 'eslint-config-xo' '[16].rules'
	'ts/no-unused-vars': 'off',
	// End expansion
}

// (xo/typescript-test-declaration)
export const xoTypescriptTestRules: Rules = {
	// Begin expansion 'eslint-config-xo' '[17].rules'
	'ts/no-unsafe-call': 'off',
	'ts/no-confusing-void-expression': 'off',
	'ts/no-unnecessary-type-arguments': 'off',
	'ts/no-unsafe-argument': 'off',
	// End expansion
}

// (xo/typescript-jsx)
export const xoTsxRules: Rules = {
	// Begin expansion 'eslint-config-xo' '[18].rules'
	'ts/naming-convention': [
		'error',
		{
			selector: [
				'variable',
				'function',
				'classProperty',
				'objectLiteralProperty',
				'parameterProperty',
				'classMethod',
				'objectLiteralMethod',
				'typeMethod',
				'accessor',
			],
			format: ['strictCamelCase', 'StrictPascalCase'],
			leadingUnderscore: 'allowSingleOrDouble',
			trailingUnderscore: 'allow',
		},
		{
			selector: 'variable',
			modifiers: ['const', 'global'],
			format: ['strictCamelCase', 'StrictPascalCase', 'UPPER_CASE'],
			leadingUnderscore: 'allowSingleOrDouble',
			trailingUnderscore: 'allow',
			filter: { regex: '[- ]', match: false },
		},
		{
			selector: 'classProperty',
			modifiers: ['static', 'readonly'],
			format: ['strictCamelCase', 'StrictPascalCase', 'UPPER_CASE'],
			leadingUnderscore: 'allowSingleOrDouble',
			trailingUnderscore: 'allow',
			filter: { regex: '[- ]', match: false },
		},
		{ selector: 'typeLike', format: ['StrictPascalCase'] },
		{ selector: 'interface', filter: '^[A-HJ-Z]', format: ['StrictPascalCase'] },
		{ selector: 'typeParameter', filter: '^T$|^[A-Z][A-Za-z]+$', format: ['StrictPascalCase'] },
		{
			selector: [
				'classProperty',
				'objectLiteralProperty',
				'parameterProperty',
				'classMethod',
				'objectLiteralMethod',
				'typeMethod',
				'accessor',
			],
			format: null,
			modifiers: ['requiresQuotes'],
		},
	],
	// End expansion
}
