import { knipConfig } from '@kitschpatrol/knip-config'

export default knipConfig({
	ignore: ['**/init/**', 'test/fixtures/**'],
	ignoreBinaries: ['ksdiff'],
	ignoreDependencies: [
		'@kitschpatrol/cspell-config',
		'@kitschpatrol/eslint-config',
		'@kitschpatrol/knip-config',
		'@kitschpatrol/mdat-config',
		'@kitschpatrol/prettier-config',
		'@kitschpatrol/remark-config',
		'@kitschpatrol/repo-config',
		'@kitschpatrol/stylelint-config',
		'@kitschpatrol/typescript-config',
		'@prettier/plugin-php',
		'@prettier/plugin-ruby',
		'@prettier/plugin-xml',
		'@types/eslint-config-prettier',
		'@types/react',
		'case-police',
		'chalk',
		'cspell-lib',
		'cspell',
		'eslint-config-prettier',
		'eslint-config-xo-typescript',
		'globby',
		'mdat',
		'prettier-plugin-astro',
		'prettier-plugin-packagejson',
		'prettier-plugin-sh',
		'prettier-plugin-sql',
		'prettier-plugin-svelte',
		'prettier-plugin-tailwindcss',
		'prettier-plugin-toml',
		'stylelint-config-html',
		'stylelint-config-standard',
		'stylelint',
	],
})
