allowBuilds:
  esbuild: true
  unrs-resolver: true
ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - '@kitschpatrol/safe-stable-stringify@2.5.0-fork.2'
  - 'lognow@0.8.5'
  - 'mdat-plugin-cli-help@3.4.1'
  - 'mdat@3.6.2'
  - 'metascope@0.12.2'
  - 'read-pyproject@0.4.1'
  - 'remark-mdat@3.1.1'
overrides:
  normalize-package-data: ^9.0.0
packages:
  - packages/*
peerDependencyRules:
  allowedVersions:
    # Remove once the installed version declares ESLint 10 support.
    # https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/1075
    # https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/1081
    eslint-plugin-jsx-a11y@6>eslint: ^10.0.0
publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
  - 'case-police'
