name: Check Links

on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # Checks for broken links in all the repository's Markdown files
      - name: Check Repository Links
        uses: JustinBeckwith/linkinator-action@b01779287d9a8423ef7d222fb1c3ba5a2b11ac58 # v2.4.4
        with:
          paths: '**/*.md'
          requireHttps: error
          retry: true
          retryErrors: true
          verbosity: info
          statusCodes: '{"3xx": "info", "429":"skip"}'

      # Checks for broken links on the repository's website
      # Only runs if GitHub website link does NOT point back to the GitHub repository itself
      - name: Check Website Links
        uses: JustinBeckwith/linkinator-action@b01779287d9a8423ef7d222fb1c3ba5a2b11ac58 # v2.4.4
        if: >-
          github.event.repository.homepage &&
          github.event.repository.homepage != format('{0}/{1}', github.server_url, github.repository)
        with:
          paths: ${{ github.event.repository.homepage }}
          recurse: true
          concurrency: 20
          requireHttps: error
          retry: true
          retryErrors: true
          verbosity: info
